routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $n_users = User::all();
    return view('welcome', compact('n_users'));
});

Route::get('/video', function () {
    return view('article.video');
});

// Route::get('welcome', 'HomeController@welcome')->name('welcome');

Route::get('mail', function () {
    Mail::send('message', array('name' => 'Arjun'), function ($messages) {
        $messages->to('webkoundo@gmail.com', 'Moses Bula')->subject('BookCase en oeuvre');
    });
});

//  Route auth avec verification de mail a utilisé en dev
// Auth::routes();

//  Route auth avec verification de mail a utilisé en prod
Auth::routes(['verify' => true]);

//  Route auth avec verification de mail a utilisé en prod
// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/choice', 'UserController@choice_compte')->name('choice');

//Après access choisir quel chemin prendre
Route::get('/path_user{user}', 'UserController@direction_user')->name('path_user');

// Pour le teacher
Route::resource('teacher', 'TeacherController');
Route::post('verif_teacher', 'TeacherController@verification')->name('verif_teacher');

Route::get('inquiry/{code}', 'TeacherController@inquiry')->name('inquiry');

Route::get('/teacher_create/{user}', 'TeacherController@student_create')->name('teacher');


// zone UNIVERSITY
Route::resource('university', 'UniversityController');
Route::resource('agreement', 'AgreementController');
Route::get('agreement_library', 'AgreementController@library')->name('agreement_library');

// library
Route::resource('library', 'LibraryController');

// End library

// Valider la demande de creation ave transmission de cote d'access
    
Route::get('validation/{code}', 'AgreementController@agreement')->name('validation');
Route::get('library_validate/{code}', 'AgreementController@validate_library')->name('library_validate');

// Route::post('v_agreement', 'AgreementController@validateagreement')->name('v_agreement');

// Route::get('dashboard', 'UniversityController@dashboard')->name('dashboard');

// Gestion d'artile d'une université (TFC,TFE, Memoire)
// Creation en function du dernier user inserer
Route::get('/student_create/{user}', 'StudentController@student_create')->name('student_create');
//REST student
Route::resource('student', 'StudentController');


Route::middleware('auth')->group(function(){
//  Route auth avec verification de mail a utilisé en dev
Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile')->name('profile');
Route::post('profile', 'UserController@update_profile')->name('profile');

// ZONE ETUDIANT

// connaitre la liste du corps professoral de l'university d'etude de l'etudiant
Route::get('univ_teacher', 'StudentController@univ_teacher')->name('univ_teacher');

// connaitre les details pertinents d'un corps professoral
Route::get('show_teacher/{id}', 'StudentController@show_teacher')->name('show_teacher');

// liste des news private
Route::get('private_news', 'StudentController@privatenews')->name('private_news');

// pour placer un article dans ses favoris
Route::get('articleFavoriteStoreToogle/{id}', 'ArticleController@article_favorite_store_toggle')->name('articleFavoriteStoreToogle');

//  End ZONE ETUDIANT

// news
Route::resource('news', 'NewsController');

Route::get('news_like/{id}', 'NewsController@like_to')->name('news_like');
Route::get('news_like_show/{id}', 'NewsController@like_to_show')->name('news_like_show');
Route::get('news_join_show/{id}', 'NewsController@join_to_show')->name('news_join_show');
Route::get('news_join/{id}', 'NewsController@join_to')->name('news_join');
Route::post('commentNews', 'NewsController@commetNews')->name('commentNews');

// Route::get('news_join/{id}','NewsController@join_to');

Route::resource('activation', 'ActivationController');
Route::get('activation_store/{id}', 'ActivationController@stor')->name('activation_store');
Route::get('act_destroy/{id}', 'ActivationController@act_destroy')->name('act_destroy');

//pedrien
Route::get('student_artcles', 'TeacherController@student_articles')->name('student_articles');

Route::get('dashboard', 'TeacherController@dashboard')->name('dashboard');

    // Zone article
    Route::resource('article', 'ArticleController');
    // delete article
    Route::get('article_delete/{id}', 'ArticleController@destroy')->name('article_delete');

    // Pour brouillon
    Route::get('draft', 'ArticleController@draft')->name('draft');

    // publication brouillon
    Route::post('draft_publish/{id}', 'ArticleController@draft_publish')->name('draft_publish');

    // Pour le welcome_article
    Route::post('article_home', 'ArticleController@article_welcome')->name('article_home');

    // Pour article : all, free et payant
    Route::get('article_show/{type}', 'ArticleController@article_show')->name('article_show');

  

    // Pour article :: all (par collections)
    Route::get('ArticleCollection', 'ArticleController@article_collections')->name('ArticleCollection'); //ici

    // Pour article : article_recent
    Route::get('article_recent', 'ArticleController@article_recent')->name('article_recent');

    // Pour article : article favorites
    Route::get('ArticleFavorites', 'ArticleController@article_favorites')->name('ArticleFavorites');

    // Pour article : download
    Route::get('download_file/{id}', 'ArticleController@download_file')->name('download_file');

    // Pour article payer
    Route::get('article_payer/{type}', 'ArticleController@paiement_recent')->name('Payment');

    // Article a payer
    Route::get('pay/{id}', 'ArticleController@payments')->name('pay');

    // Fin de zone ARTICLE

    // Library

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');
    // payer l'abonnement d'un bundle d'une library
    Route::post('pay_abonnement', 'LibraryController@pay_abonnement')->name('pay_abonnement');
    // pour student et autres utilisateurs en dehors de l'administration de la library
    Route::get('s_libraries/{datav?}', 'StudentController@s_libraries')->name('studentLibrary');

    // dashboard library
    Route::get('dashboardLibrary', 'LibraryController@dashboard')->name('dashboardLibrary');

    // End library


    // Teacher
    // get
    Route::get('TeacherRessource', 'UniversityController@teacher_ressource')->name('TeacherRessource');
    //enregistrer
    Route::post('teacherstore', 'UniversityController@teacherstore_reference')->name('teacherstore');
    // End Teacher


    // Dashbord de l'university
    Route::get('wall', 'UniversityController@dashboard')->name('wall');

    //get
    Route::get('ArticleRessource', 'UniversityController@article_ressource')->name('ArticleRessource');

    // Visualisation de toutes les univcersités par la communauté bookcase
    Route::get('universities', 'UniversityController@university_all')->name('universities');

    // Gestion student
    Route::get('StudentRessource', 'UniversityController@student_ressource')->name('StudentRessource');

    // get:  document
    Route::get('CollectionRessource','UniversityController@promotion_ressource')->name('CollectionRessource');

    // get:  department
    Route::get('DepartmentRessource','UniversityController@department_ressource')->name('DepartmentRessource');

    // get: faculty
    Route::get('FacultyRessource','UniversityController@faculty_ressource')->name('FacultyRessource');


    // Get: Facultés/Departements/Promotion d'une université
    Route::get('InstitutionRessource', 'UniversityController@instutition_ressource')->name('InstitutionRessource');

    // store Instutition : Faculté,Department et collection ou promotion
    Route::post('InstitutionStore','UniversityController@storeinstitution')->name('InstitutionStore');

    //Enregistrer une news
    // get
    Route::get('storeNews', 'UniversityController@storeNews')->name('storeNews');

    // enregistrer
    Route::post('newstore', 'UniversityController@store_news')->name('newstore');


    Route::resource('Cart', 'CartController');
    Route::get('add_panier/{id}', 'CartController@storeart')->name('add_panier');
    Route::get('CartEmpty', 'CartController@CartEmpty')->name('CartEmpty');
    Route::get('CartDestroy/{id}', 'CartController@destroy')->name('CartDestroy');
    Route::post('CartPay', 'CartController@CartPay')->name('CartPay');
    Route::post('PayConfirm', 'CartController@PayConfirm')->name('PayConfirm');
});

app/Article.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Article extends Model
{
    protected $fillable = ['article_name', 'slug', 'publishing_at', 'author', 'domain_exploitation', 'file','video', 'edition', 'price', 'teacher_id','membership','library_id','status_id'];

    protected $dates = ['publishing_at'];

    /* Relations */
    public function teacher()
    {
        return $this->belongsTo('App\Teacher');
    }

    public function library()
    {
        return $this->belongsTo('App\Library');
    }

    public function status()
    {
        return $this->belongsTo('App\Status');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'article_categories');
    }

    public function studentarticles()
    {
        return $this->hasMany('App\StudentArticle');
    }


    public function documents()
    {
        return $this->belongsToMany('App\Document', 'document_articles');
    }

    public function pay_article()
    {
        return $this->belongsTo('App\PayArticle');
    }

    public function users()
    {
        return $this->belongsToMany('App\User', 'student_articles');
    }

    public function exchang()
    {
        return $this->belongsTo('App\Excahng');
    }

    /* scope*/


    /* setters et getters */

    public function setSlugAttribute($value)
    {
        // dd(trim($value));

        $this->attributes['slug'] =  str_replace(
            " ",
            " - ",
            trim($value) . ' ' .
                strtoupper(explode('.', $this->attributes['article_name'])[0]) . ' ' . strtolower(explode('.', $this->attributes['article_name'])[0]) . ' ' .
                strtoupper($this->attributes['author']) . ' ' . strtolower($this->attributes['author']) . ' ' .
                $this->attributes['edition'] . ' ' . $this->attributes['price']
        );
    }

    // public function setDomainExploitationAttribute($value)
    // {
    //     $this->attributes['domain_exploitation'] = str_replace(",", " - ",  strtoupper($value) . ',' . strtolower($value) . ',' . ucfirst($value));
    // }

    /* fin setters et getters */

    /* recherche des articles par un contains ($q) */
    public function scopeSearchByArticle($query, $q)
    {
        return $query->where('article_name', 'LIKE', '%' . $q . '%')
            ->orwhere('slug', 'LIKE', '%' . $q . '%')
            ->orwhere('domain_exploitation', 'LIKE', '%' . $q . '%')
            ->orderBy('article_name');
    }

    /* recherche des articles payant */
    public function scopePayArticle($query)
    {
        return $query->where('price', '>', '0');
    }

    /* recherche des articles gratuit a 0 */
    public function scopeFreeArticle($query)
    {
        return $query->where('price', '0');
    }

    /* Recherche article public */
    public function scopePublicArticle($query)
    {
        return $query->where('status_id', '1');
    }

    /* Recherche article private */
    public function scopePrivatecArticle($query)
    {
        return $query->where('status_id', '2');
    }


    /* Ordre desc de la création des articles */
    public function scopePublishDesc($query)
    {
        return $query->orderBy('publishing_at', 'desc');
    }

    /* article recent d'un teacher */
    public function scopeNewsArticleDesc($query)
    {
        // Periode de 6 mois de nouveauté
        return $query->where('created_at', '>=', Carbon::now()->subDays(186))
            ->orderBy('created_at', 'desc');
    }
}

resources/views/article/favorite.blade.php
@extends('layouts.student_layout')

@section('content_student')
    <div class="col-md-12 card_file margin" style="margin-top: 150px !important;">
        <!-- // Gratuit -->
        <div class="row mt-4">
            <div class="col-lg-3">
                <div class="card card-category">
                    <div class="card-header">
                        <form action="">
                            <input type="text" class="form-control" placeholder="Faite la recherche ici...">
                        </form>
                    </div>
                    <div class="text-left">
                        <a href="{{ route('article_show',['type'=>'all']) }}"><i class="fa fa-file-o"></i> Tous</a>
                        <a href="{{ route('article_show',['type'=>'free']) }}"><i class="fa fa-smile-o"></i> Gratuits</a>
                        <a href="{{ route('article_show',['type'=>'payant']) }}"><i class="fa fa-dollar"></i> Payants</a>
                        <a href="#"><i class="fa fa-user"></i> Auteurs</a>
                        <a href="{{ route('ArticleCollection')}}"><i class="fa fa-folder-o"></i> Collections</a>
                        <a href="{{ route('ArticleFavorites')}}"><i class="fa fa-folder-o"></i> Mes favoris</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row mt-5">
                    @foreach($articles_favorites as $article)
                        <div class="col-lg-4">
                            <div class="card card-art">
                                <div class="card-header d-flex">
                                    <div class="avatar-auteur">
                                        <img src="/storage/uploads/images/bg-3.jpg" alt="img" class="img-fluid">
                                    </div>
                                    <div class="content-auteur text-white">
                                        <h5>{{$article->author}}</h5>
                                        @if($article->membership =="LBRY")
                                        <span>{{$article->library->name_library }}</span>
                                        @else
                                        <span>{{$article->teacher->title->lampoon}}</span>
                                        @endif
                                    </div>
                                    <div class="icon">
                                        <i class="fa fa-file-pdf-o"></i>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="text-left">
                                        <h4><a class="text-secondary" href="{{route('article.show',$article->id)}}">{{ Str::limit($article->article_name, 20) }}</a></h4>
                                        @if($article->categories()->count() >0)
                                        @foreach($article->categories as $categorys)
                                        <span class="category">{{$categorys->category}}</span>
                                        @endforeach
                                        @else
                                        @endif
    
                                        <br>
                                        @if($article->documents()->count() >0)
                                        @foreach($article->documents as $collects)
                                        <span class="type">{{$collects->document_name}}</span>
                                        @endforeach
                                        @else
                                        @endif
    
                                        <br>
                                        <span class="badge badge-primary">Edition {{$article->edition}}</span>
                                        <br>
                                        @if($article->price == 0)
                                        <p class="mb-0 text-right payant" style="font-size:22px;color:#151370;">Gratuit</p>
                                        @else
                                        <p class="mb-0 text-right payant" style="font-size:22px;color:#151370;">{{$article->price}} {{$article->devise}}</p>
                                        @endif
                                        <span style="display:block;margin-top:5px"><i class="fa fa-download"></i> 10000 Téléchargements</span>
                                    </div>
                                </div>
                                <!-- <div class="card-footer">
                                    @if($article->price == 0)
                                    <a href="{{route('download_file',$article->id)}}" class="btn btn-primary btn-sm btn-download-sm"><i class="fa fa-download"></i> Télécahger</a>
                                    {{-- <a href=""><i class="fa fa-download"></i> Télélchager</a> --}}
                                    @else
                                    {{-- <a href="{{route('add_panier',$article->id)}}"><i class="fa fa-cart-arrow-down"></i>Mis au panier</a>
                                    <a href="#" class="btn btn-primary btn-sm btn-achat"><i class="fa fa-dollar"></i> Acheter</a> --}}
                                    @if($article->video !=null)
                                    <span class="btn-video">
                                        <i class="fa fa-play"></i>
                                        <span class="Tooltip-sm">Voir la video</span>
                                    </span>
                                    @endif
    
                                    <a href="{{route('add_panier',$article->id)}}" class="btn btn-cart ml-2 btn btn-primary btn-sm btn-achat">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart text-white" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                        </svg>
                                    </a>
                                    @endif
                                </div> -->
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection


@section('script_article')
<script>
    $(function() {

        $("#search_article").keyup(function() {

            var search = $(this).val();

            search = $.trim(search);

            $(".title_article").removeClass("color_v");
            $(".title_article").parent().parent().parent().parent().css("display", "none");


            if (search != "") {

                $(".title_article:contains('" + search + "')").addClass("color_v");
                $(".title_article:contains('" + search + "')").show();
                $(".title_article:contains('" + search + "')").parent().parent().parent().parent().css("display", "flex");

            } else {
                $(".title_article").removeClass("color_v");
                $(".title_article").parent().parent().parent().parent().css("display", "flex");
            }


        });
    });
</script>
@endsection

resources/views/article/pay.blade.php
@extends('layouts.student_layout')

@section('content_student')

<div class="col-md-9 card p-5 " style="margin-top:22rem !important;">
    <div class="justify-content-center">
        <h4 class="h4 text-center text-secondary">
            Oups !!!, Paiement en mode maintenance
        </h4>
    </div>

    <!-- <div class="col-md-12 text-justify-space-around ml-5">
        <span><a href="{{ route('Payment',['type'=>'recent']) }}">Récent</a> / </span>
        <span><a href="{{ route('Payment',['type'=>'all']) }}">Tout</a></span>
    </div> -->
</div>

@endsection

resources/views/article/recent.blade.php
@extends('layouts.student_layout')

@section('content_student')

@if($recent_articles->count() == 0)

<div class="container-fluid p-4 ml-4 recent_phone" style="margin-top:5rem;">
    <div class="text-left">
        <h1 class="title mb-4 ml-md-5">Articles Récents</h1>
    </div>
    <div class="text-center">
        <i class="fa fa-files-o" style="font-size:200px;"></i>
        <P>Vous disposez d'aucun article pour le moment, Veuillez découvrir notre galerie d'articles </p>
        <a href="{{ route('article.index')}}" class="btn-primary btn-sm btn">Explorer la galerie Bookcase</a>
    </div>
</div>



@else
<div class="col-md-9 card_file margin">

    <div class="row justify-content-center">
        <div class="col-10 col-md-11 col-sm-10 col-lg-12">
            <p class="text-justify h2 p_titile_article title">Articles Récents</p>
        </div>


        <div class="container-fluid">

            <!-- // Gratuit -->
            <div class="row">

                @foreach($recent_articles as $art)


                <div class="col-md-6 col_hover col-lg-4">
                    <div class="row">
                        <div class="col-md-6 col-sm-5 col-5">
                            <div class="card" style="padding:30px 20px;overflow:hidden;">
                                @if($art->article->price == 0)
                                <span class="prix bg-success">Gratuit</span>
                                @else
                                <span class="num">{{$art->article->price}}</span>
                                <span class="prix bg-warning" style="background:#ffa500!important;">Payant</span>
                                @endif
                                <div class="text-center">
                                    <i class="fa fa-file-pdf-o " style="font-size:60px;"></i>
                                </div>
                            </div>
                        </div>



                        <div class="col-md-6 col-sm-5 col-5" style="margin-top:50px;">
                            <div class="text-left">
                                <!-- <a href="{{route('article.show',$art->article->id)}}"> -->
                                <h6 class="title_article">
                                    {{ Str::limit($art->article->article_name, 20) }}

                                </h6>
                                <!-- </a> -->
                                <p class="paragraph-article">Ed. {{$art->article->edition}}</p>
                                <p class="paragraph-article">At. {{$art->article->author}}</p>

                                @if($art->article->categories->count() >0)
                                @foreach($art->article->categories as $categorys)
                                <p class="paragraph-article">{{$categorys->category}}</p>
                                @endforeach
                                @else
                                <!-- <p class="paragraph-article">Cat. Inconnu</p> -->
                                @endif

                                @if($art->article->documents->count() >0)
                                @foreach($art->article->documents as $collect)
                                <p class="paragraph-article">{{$collect->document_name}}</p>
                                @endforeach
                                @else
                                <!-- <p class="paragraph-article">Collection. Inconnu</p> -->
                                @endif

                                <div class="action" style="background:#32e4cd;">
                                    <span class="action-plus"><i class="fa fa-trash-o"></i></span>
                                    <div class="show-option-plus">
                                        <a href=""><i class="fa fa-eye"></i>Voir le detail</a>
                                        <a href=""><i class="fa fa-download"></i> Télélchager</a>
                                    </div>
                                </div> 

                            </div>

                        </div>

                        <div class="text-right">

                        </div>
                    </div>
                </div>

                @endforeach
            </div>

        </div>

    </div>
</div>

@endif

@endsection


@section('script_article')
<script>
    $(function() {

        $("#search_article").keyup(function() {
            var search = $(this).val();

            search = $.trim(search);

            $(".title_article").removeClass("color_v");
            $(".title_article").parent().parent().parent().css("display", "none");

            if (search != "") {
                $(".title_article:contains('" + search + "')").addClass("color_v");
                $(".title_article:contains('" + search + "')").show();

                $(".title_article:contains('" + search + "')").parent().parent().parent().css("display", "flex");

            } else {
                $(".title_article").removeClass("color_v");
                $(".title_article").parent().parent().parent().css("display", "flex");
            }


        });
    });
</script>
@endsection

resources/views/article/search_welcome_article.blade.php
@extends('layouts.app',['title' => 'Article'])

@section('content')

<div class="container" style="margin-top:100px;">
    <div class="row justify-content-around">

        <div class="col-md-9 card_file text-center">
            <form method="POST" action="{{ route('article_home')}}">
                @csrf
                <div class="col-md-12 mb-3 mt-4 col-11 col-sm-11 col-lg-12">
                    <div class="form-group col-md-12 col-lg-12 ">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <button class="btn btn-outline-secondary" type="button" id="button-addon1" style="border:none;"><i class="fa fa-search"></i></button>
                            </div>
                            <input type="search" name="search_article" id="search_article" class="form-control form-control-lg" placeholder="Chercher cours, tfc, mémoire, livre etc..." aria-label="Example text with button addon" aria-describedby="button-addon1">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
    <div class="col-md-12 card_file text-center" style="margin-top:60px;">

@if($articles->count() == 0)
<div class="container">
    <div class="py-4 p_color_75">
        <div class="row justify-content-center">

            <h2>Aucun contenu n'est disponible avec votre recherche</h2>

        </div>
    </div>
</div>

@else

<h3 class="h3 text-left p_titile_article">Contenus recherchés</h3>

<div class="row">
    

        @foreach($articles as $article)


        <div class="col-md-6 col_hover col-lg-4">
            <div class="row">
                <div class="col-md-6 col-sm-5 col-5">
                    <div class="card" style="padding:30px 20px;overflow:hidden;">

                        <span class="prix bg-success">Gratuit</span>

                        <div class="text-center">
                            <i class="fa fa-file-pdf-o " style="font-size:60px;"></i>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-sm-5 col-5" style="margin-top:50px;">
                    <div class="text-left">


                        @if (Route::has('login'))
                        @auth
                        <a href="{{route('article.show',$article->id)}}">
                            <h6 class="title_article">
                                {{ Str::limit($article->article_name, 20) }}
                            </h6>
                        </a>
                        @else

                        <a href="{{route('login')}}">
                            <h6 class="title_article">
                                {{ Str::limit($article->article_name, 20) }}
                            </h6>
                        </a>
                        @endauth
                        @endif

                        <p class="paragraph-article">Ed. {{$article->edition}}</p>
                        <p class="paragraph-article">At. {{$article->author}}</p>

                        @if($article->categories()->count() >0)
                        @foreach($article->categories as $categorys)
                        <p class="paragraph-article">{{$categorys->category}}</p>
                        @endforeach
                        @else
                        <!-- <p class="paragraph-article">Cat. Inconnu</p> -->
                        @endif

                        @if($article->documents()->count() >0)
                        @foreach($article->documents as $collects)
                        <p class="paragraph-article">{{$collects->document_name}}</p>
                        @endforeach
                        @else

                        <!-- <p class="paragraph-article">Collection. Inconnu</p> -->
                        @endif


                        @if (Route::has('login'))
                        @auth
                        <button class="btn btn-sm btn-download btn-primary btn-login fadeIn" style="font-size:8px;"><i class="fa fa-download"></i>
                            <a href="{{ route('download_file',$article->id)}}">
                                Télécharger
                            </a>
                        </button>
                        @else

                        <button class="btn btn-sm btn-download btn-primary btn-login fadeIn" style="font-size:8px;"><i class="fa fa-download"></i>
                            <a href="{{ route('login')}}">
                                Télécharger
                            </a>
                        </button>
                        @endauth
                        @endif



                    </div>

                </div>

                <div class="text-right">

                </div>
            </div>
        </div>

        @endforeach
    
</div>

@endif

<div class="row mt-5">
    <div class="col-md-12 mb-4">
        @if (Route::has('login'))
        @auth
        <a href="{{ route('article.index')}}" class="btn btn-info" style=" color:white !important;">Decouvrez notre galerie d'articles </a>
        @else
        <a href="{{ route('login')}}" class="btn btn-info" style="color:white !important;">Decouvrez notre galerie d'articles </a>
        @endauth
        @endif
    </div>
</div>
</div>
    </div>
</div>

@endsection