routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $n_users = User::all();
    return view('welcome', compact('n_users'));
});

Route::get('/video', function () {
    return view('article.video');
});

// Route::get('welcome', 'HomeController@welcome')->name('welcome');

Route::get('mail', function () {
    Mail::send('message', array('name' => 'Arjun'), function ($messages) {
        $messages->to('webkoundo@gmail.com', 'Moses Bula')->subject('BookCase en oeuvre');
    });
});

//  Route auth avec verification de mail a utilisé en dev
// Auth::routes();

//  Route auth avec verification de mail a utilisé en prod
Auth::routes(['verify' => true]);

//  Route auth avec verification de mail a utilisé en prod
// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/choice', 'UserController@choice_compte')->name('choice');

//Après access choisir quel chemin prendre
Route::get('/path_user{user}', 'UserController@direction_user')->name('path_user');

// Pour le teacher
Route::resource('teacher', 'TeacherController');
Route::post('verif_teacher', 'TeacherController@verification')->name('verif_teacher');

Route::get('inquiry/{code}', 'TeacherController@inquiry')->name('inquiry');

Route::get('/teacher_create/{user}', 'TeacherController@student_create')->name('teacher');


// zone UNIVERSITY
Route::resource('university', 'UniversityController');
Route::resource('agreement', 'AgreementController');
Route::get('agreement_library', 'AgreementController@library')->name('agreement_library');

// library
Route::resource('library', 'LibraryController');

// End library

// Valider la demande de creation ave transmission de cote d'access
    
Route::get('validation/{code}', 'AgreementController@agreement')->name('validation');
Route::get('library_validate/{code}', 'AgreementController@validate_library')->name('library_validate');

// Route::post('v_agreement', 'AgreementController@validateagreement')->name('v_agreement');

// Route::get('dashboard', 'UniversityController@dashboard')->name('dashboard');

// Gestion d'artile d'une université (TFC,TFE, Memoire)
// Creation en function du dernier user inserer
Route::get('/student_create/{user}', 'StudentController@student_create')->name('student_create');
//REST student
Route::resource('student', 'StudentController');


Route::middleware('auth')->group(function(){
//  Route auth avec verification de mail a utilisé en dev
Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile')->name('profile');
Route::post('profile', 'UserController@update_profile')->name('profile');

// ZONE ETUDIANT

// connaitre la liste du corps professoral de l'university d'etude de l'etudiant
Route::get('univ_teacher', 'StudentController@univ_teacher')->name('univ_teacher');

// connaitre les details pertinents d'un corps professoral
Route::get('show_teacher/{id}', 'StudentController@show_teacher')->name('show_teacher');

// liste des news private
Route::get('private_news', 'StudentController@privatenews')->name('private_news');

// pour placer un article dans ses favoris
Route::get('articleFavoriteStoreToogle/{id}', 'ArticleController@article_favorite_store_toggle')->name('articleFavoriteStoreToogle');

//  End ZONE ETUDIANT

// news
Route::resource('news', 'NewsController');

Route::get('news_like/{id}', 'NewsController@like_to')->name('news_like');
Route::get('news_like_show/{id}', 'NewsController@like_to_show')->name('news_like_show');
Route::get('news_join_show/{id}', 'NewsController@join_to_show')->name('news_join_show');
Route::get('news_join/{id}', 'NewsController@join_to')->name('news_join');
Route::post('commentNews', 'NewsController@commetNews')->name('commentNews');

// Route::get('news_join/{id}','NewsController@join_to');

Route::resource('activation', 'ActivationController');
Route::get('activation_store/{id}', 'ActivationController@stor')->name('activation_store');
Route::get('act_destroy/{id}', 'ActivationController@act_destroy')->name('act_destroy');

//pedrien
Route::get('student_artcles', 'TeacherController@student_articles')->name('student_articles');

Route::get('dashboard', 'TeacherController@dashboard')->name('dashboard');

    // Zone article
    Route::resource('article', 'ArticleController');
    // delete article
    Route::get('article_delete/{id}', 'ArticleController@destroy')->name('article_delete');

    // Pour brouillon
    Route::get('draft', 'ArticleController@draft')->name('draft');

    // publication brouillon
    Route::post('draft_publish/{id}', 'ArticleController@draft_publish')->name('draft_publish');

    // Pour le welcome_article
    Route::post('article_home', 'ArticleController@article_welcome')->name('article_home');

    // Pour article : all, free et payant
    Route::get('article_show/{type}', 'ArticleController@article_show')->name('article_show');

  

    // Pour article :: all (par collections)
    Route::get('ArticleCollection', 'ArticleController@article_collections')->name('ArticleCollection'); //ici

    // Pour article : article_recent
    Route::get('article_recent', 'ArticleController@article_recent')->name('article_recent');

    // Pour article : article favorites
    Route::get('ArticleFavorites', 'ArticleController@article_favorites')->name('ArticleFavorites');

    // Pour article : download
    Route::get('download_file/{id}', 'ArticleController@download_file')->name('download_file');

    // Pour article payer
    Route::get('article_payer/{type}', 'ArticleController@paiement_recent')->name('Payment');

    // Article a payer
    Route::get('pay/{id}', 'ArticleController@payments')->name('pay');

    // Fin de zone ARTICLE

    // Library

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');
    // payer l'abonnement d'un bundle d'une library
    Route::post('pay_abonnement', 'LibraryController@pay_abonnement')->name('pay_abonnement');
    // pour student et autres utilisateurs en dehors de l'administration de la library
    Route::get('s_libraries/{datav?}', 'StudentController@s_libraries')->name('studentLibrary');

    // dashboard library
    Route::get('dashboardLibrary', 'LibraryController@dashboard')->name('dashboardLibrary');

    // End library


    // Teacher
    // get
    Route::get('TeacherRessource', 'UniversityController@teacher_ressource')->name('TeacherRessource');
    //enregistrer
    Route::post('teacherstore', 'UniversityController@teacherstore_reference')->name('teacherstore');
    // End Teacher


    // Dashbord de l'university
    Route::get('wall', 'UniversityController@dashboard')->name('wall');

    //get
    Route::get('ArticleRessource', 'UniversityController@article_ressource')->name('ArticleRessource');

    // Visualisation de toutes les univcersités par la communauté bookcase
    Route::get('universities', 'UniversityController@university_all')->name('universities');

    // Gestion student
    Route::get('StudentRessource', 'UniversityController@student_ressource')->name('StudentRessource');

    // get:  document
    Route::get('CollectionRessource','UniversityController@promotion_ressource')->name('CollectionRessource');

    // get:  department
    Route::get('DepartmentRessource','UniversityController@department_ressource')->name('DepartmentRessource');

    // get: faculty
    Route::get('FacultyRessource','UniversityController@faculty_ressource')->name('FacultyRessource');


    // Get: Facultés/Departements/Promotion d'une université
    Route::get('InstitutionRessource', 'UniversityController@instutition_ressource')->name('InstitutionRessource');

    // store Instutition : Faculté,Department et collection ou promotion
    Route::post('InstitutionStore','UniversityController@storeinstitution')->name('InstitutionStore');

    //Enregistrer une news
    // get
    Route::get('storeNews', 'UniversityController@storeNews')->name('storeNews');

    // enregistrer
    Route::post('newstore', 'UniversityController@store_news')->name('newstore');


    Route::resource('Cart', 'CartController');
    Route::get('add_panier/{id}', 'CartController@storeart')->name('add_panier');
    Route::get('CartEmpty', 'CartController@CartEmpty')->name('CartEmpty');
    Route::get('CartDestroy/{id}', 'CartController@destroy')->name('CartDestroy');
    Route::post('CartPay', 'CartController@CartPay')->name('CartPay');
    Route::post('PayConfirm', 'CartController@PayConfirm')->name('PayConfirm');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['student_name', 'sex', 'phone', 'domain_exploitation', 'type_student_id', 'user_id'];

    // protected $datas=['birth_at'];

    /* relations */

    public function type_student()
    {
        return $this->belongsTo('App\Type_student');
    }

    public function user()
    {
        return  $this->belongsTo('App\User');
    }

    // public function articles(){

    //     return $this->belongsToMany('App\Article');
    // }

    //getters et setters
    public function setStudentNameAttribute($value)
    {
        $this->attributes['student_name'] = ucfirst($value);
    }


    public function setDomainExploitationAttribute($value)
    {
        $this->attributes['domain_exploitation'] = str_replace(",", "-",  strtoupper($value) . ',' . strtolower($value)). "all-tout-tous";
    }
}

resources/views/student/create.blade.php
@section('style')
<link href="{{ asset('css/_style.css') }}" rel="stylesheet">
@endsection

@extends('layouts.app',['title' => 'Student'])

@section('content')
<div class="bg-choice">
    <div class="container">
        
        <div class="row justify-content-around">
            <div class="col-md-10 col-lg-4 margin" style="margin-top: 40px !important;">
            <ul id="progress">
                    <li>Account Setup</li>
                    <li class="active">Personal Details</li>

                </ul>

                <div class="card slideBox1" style="border-radius: 10px;padding:20px 30px;z-index:1;background:white;">
                    <div class="text-left mb-4">

                        <h2 class="heading title-form page2" style="font-size: 28px;">{{$user->rule->rule}} Account</h2>

                    </div>

                    <div class="card-body">
                        
                        <form method="POST" action="{{ route('student.store')}}">
                            @csrf
                            <div class="form-group row mb-4">
                                
                                <div class="col-md-12">
                                    <label for="student_name">Nom Complet</label>
                                    <input id="student_name" type="text" class="form-control" name="student_name" required  value="{{ old('student_name')}}">
                                    {!! $errors->first('student_name','<p class="error-msg">:message</p>') !!}
                                    <!-- @error('student_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror -->
                                </div>
                            </div>

                            <div class="form-group row  mb-4 ml-2">


                                <label for="sex" class="col-md-6 text-left col-6 col-lg-6">
                                    <input type="radio" name="sex" id="sex" class="form-check-input " checked="true" value="Homme">Homme <i class="fa fa-male"></i>
                                </label>

                                <label for="sex" class="col-md-6  form-check-label text-left col-6 col-lg-6">
                                    <input type="radio" name="sex" id="sex" class="form-check-input" value="Femme">Femme <i class="fa fa-female"></i>
                                </label>

                                @error('sex')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <!-- <div class="form-group form-check-inline">
                           
                        </div> -->


                            <div class="form-group row  mb-4">
                                
                                <div class="col-md-12">
                                    <label for="phone">Téléphone</label>
                                    <input id="phone" type="tel" class="form-control" name="phone"  required autocomplete="phone">
                                </div>

                            </div>

                            <div class="form-group row  mb-4">
                                
                                <div class="col-md-12">
                                    <label for="domain_exploitation">domain d'étude <span class="info" title="pedrieieieieiieeieieieieieieieieiieeiei" data-toggle="tooltip" data-placement="top"><i class="fa fa-info"></i></span></label>
                                    <textarea name="domain_exploitation" id="domain_exploitation" class=" @error('domain_exploitation') is-invalid @enderror form-control" required></textarea>
                                    <input type="hidden" name="user_id" id="user_id" value="{{$user->id}}">
                                    @error('domain_exploitation')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="text-left">
                                <small>En cliquant sur Sauvegarder les infos, I agree that I have read and accepted the <span style="color:#6f42c1">Terms of Use</span> and <span style="color:#6f42c1">Privacy Policy</span>.</small>
                            </div>
                            <!-- <div class="form-group row ">
                                
                                <div class="col-md-12 mb-4">
                                    <label for="type_student">Type student</label>
                                    <select class="form-control" id="type_student_id" name="type_student_id">
                                        @foreach($type_etudiant as $etudiant)
                                        <option value="{{$etudiant->id }}">{{$etudiant->type_student }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <br>
                            </div> -->
                            <button type="submit" class="btn btn-primary btn-block btn-auth btn-login btn-float">
                                <span class="spinner-border-sm rotate_spinner" role="status" aria-hidden="true" ></span>
                                <span class="spam">Sauvegarder les infos</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center mt-4">
            <small class="text-secondary">BookCase <?php echo strftime('%Y') ?> &copy;</small>

        </div>
    </div>
</div>
@endsection

resources/views/student/library_show.blade.php
@inject('dataCore','App\Utilities\CoreData')
<!-- FQN le Full Qualy Name -->

@extends('layouts.student_layout')

@section('content_student')
<div class="col-md-12 card_file margin" style="margin-top: 150px !important;">

    {{-- <div class="container-fluid"> --}}
    <!-- // Gratuit -->
    <div class="row mt-4">
        <div class="col-lg-3">
            <div class="card card-category">
                <div class="card-header">
                    <form action="">
                        <input type="text" class="form-control" placeholder="Faite la recherche ici...">
                    </form>
                </div>
                <div class="text-left">
                    {{-- <a href="{{ route('article_show',['type'=>'free']) }}"><i class="fa fa-smile-o"></i> Gratuits</a>
                    <a href="{{ route('article_show',['type'=>'payant']) }}"><i class="fa fa-dollar"></i> Payants</a> --}}
                    <a href="{{ route('studentLibrary',"MFB")}}"><i class="fa fa-smile-o"></i> Mes Favoris</a>
                    <a href="{{ route('ArticleCollection')}}"><i class="fa fa-folder-o"></i> Mes abonnements</a>
                </div>
            </div>
        </div>
        {{-- // Datas articles bibliothèque --}}
        <div class="col-lg-9">
            @if($titles=="ACB")
            {{-- // Pour le visuel des datas non abonnements ACB: Au coeur de biblio --}}
            <h2 class="mx-md-3 p_titile_article">Au coeur des bibliothèques</h2>
            @else
            {{-- Pour des datas favorites des bibliothèques --}}
            <h2 class="mx-md-3 p_titile_article">Mes favoris des bibliothèques</h2>
            @endif

            <div class="row mt-5">
                @foreach($articles as $article)
                <div class="col-lg-4">
                    <div class="card card-book" id="card-book{{$article->id}}">
                        <div class="edition">
                            Edition {{ $article->edition}}
                        </div>
                        <div class="text-left">
                            <div class="icon-book">
                                <i class="fa fa-book"></i>
                            </div>
                            <h6>{{ Str::limit($article->article_name, 20) }}</h6>
                            <p class="text-muted small">{{$article->library->name_library}}</p>
                            <hr>
                            <h6>Auteur</h6>
                            <p>
                                <span class="avatar"><img src="/storage/uploads/avatars/{{$article->library->logo}}" alt="img"></span>
                                <span>{{$article->author}}</span>
                            </p>
                            @if($dataCore->ValidateViewArticle($article->library) == true)
                            <button class="btn btn-sm text-muted">Lire le contenu</button>
                            <span class="float-right h3" id="btn_favoriteN{{$article->id}}" style="cursor: pointer;"><i class="fa fa-heart-o fa-1x"></i></span>
                            @endif
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        {{-- // End Data articles bibliothèque --}}

    </div>

    {{-- </div> --}}
    {{-- // Library --}}
    <div class="container-fluid" id="librarys">
        <div class="col-10 col-md-11 col-sm-10 col-lg-12 mb-5 my-md-5">
            <p class="text-justify h2 p_titile_article">Accroît ton savoir</p>
            <span class="text-muted">Accroit ton savoir en t'abonnant a une bibliothèque et choississez votre bundle de tarification</span>
        </div>
        <div class="row">
            @foreach ($dataCore->LibraryList() as $lib)
            <div class="col-lg-3">
                <div class="card card-biblo">
                    <div class="card-img">
                        <img src="/storage/uploads/images/{{$lib->picture}}" alt="img" class="img-cover">
                        <div class="avatar-biblo">
                            <img src="/storage/uploads/avatars/{{$lib->logo}}" alt="img">
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="text-left">
                            <a href="{{route('library.show',$lib->id)}}">
                                <h6><i class="fa fa-check"></i>{{$lib->name_library}}</h6>
                            </a>
                            <small class="mb-0 ml-1"><i class="fa fa-globe mr-1"></i><a href="" class="text-small">{{$lib->website}}</a></small> <br>
                            <span class="phone ml-1"><i class="fa fa-phone mr-1"></i>{{$lib->phone}}</span>
                        </div>
                        <div class="text-right">
                            @if($dataCore->AbonUser($lib) != 0)
                            <small class="float-left my-2 mx-2 p-1 bg-danger text-white" style="border-radius:10px;">{{$dataCore->AbonUser($lib)}} abonn.</small>
                            @endif
                            <div class="network-biblo">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                        <hr>
                        <div class="d-flex">
                            <div class="abonne text-center">
                                <span class="number">{{$dataCore->CountAbon($lib)}}</span>
                                <br>
                                <span>{{$dataCore->CountAbon($lib) <= 1 ? 'Abonné' : 'Abonnés'}}</span>
                            </div>
                            <div class="article text-center">
                                <span class="number">{{$lib->articles->count()}}</span>
                                <br>
                                <span>Ouvrages</span>
                            </div>
                            <a href="{{route('abonnements',$lib->id)}}" class="btn-primary btn-sm" style="height: 30px;margin-top: 7px;">S'abonner</a>
                        </div>

                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

@foreach ($articles as $art_lib)
<div class="show-contenu" id="show-contenu{{$art_lib->id}}">
    <div class="contenu">
        <p class="float-right text-muted small mb-3">{{$art_lib->article_name}}</p>
        <iframe id="_frame{{$art_lib->id}}" frameborder="0" style="width:100%; height:100vh;"></iframe>
    </div>
</div>
@endforeach
<div class="opacity-fond">
    <span>
        <i class="fa fa-times"></i>
    </span>
</div>


@endsection


@section('script_article')
<script>
    $(function() {

        $("#search_article").keyup(function() {

            var search = $(this).val();

            search = $.trim(search);

            $(".title_article").removeClass("color_v");
            $(".title_article").parent().parent().parent().parent().css("display", "none");


            if (search != "") {

                $(".title_article:contains('" + search + "')").addClass("color_v");
                $(".title_article:contains('" + search + "')").show();
                $(".title_article:contains('" + search + "')").parent().parent().parent().parent().css("display", "flex");

            } else {
                $(".title_article").removeClass("color_v");
                $(".title_article").parent().parent().parent().parent().css("display", "flex");
            }


        });

        @foreach($articles as $art_lib)
        $('#card-book{{$art_lib->id}} .btn').click(function() {
            $('body').toggleClass('overflow')
            $('#show-contenu{{$art_lib->id}}').toggleClass('active')
            $('.opacity-fond').toggleClass('active')
            $('#_frame{{$art_lib->id}}').prop('src', '/storage/uploads/files/{{$art_lib->article_name}}');
        })

        $('.opacity-fond span').click(function() {
            $('body').removeClass('overflow')
            $('#show-contenu{{$art_lib->id}}').removeClass('active')
            $('.opacity-fond').removeClass('active')
        })

        $('#btn_favoriteN{{$art_lib->id}}').click(function() {

            $.ajax({
                type: "GET",
                url: "{{ route('articleFavoriteStoreToogle',$art_lib->id) }}",
            });

            if ($('#btn_favoriteN{{$art_lib->id}}').children("i").hasClass('fa-heart-o')) {
                $('#btn_favoriteN{{$art_lib->id}}').children("i").removeClass('fa-heart-o text-primary');
                $('#btn_favoriteN{{$art_lib->id}}').children("i").addClass('fa-heart text-primary');
            } else {
                $('#btn_favoriteN{{$art_lib->id}}').children("i").addClass('fa-heart-o text-primary');
                $('#btn_favoriteN{{$art_lib->id}}').children("i").removeClass('fa-heart text-primary');
            }
        })
        @endforeach
    });
</script>
@endsection

resources/views/student/teacher_show.blade.php
@extends('layouts.student_layout')

@section('content_student')


<div class="col-md-12  col-sm-12 col-lg-12 margin no-padding">
    <div class="content">

        <div class="row justify-content-between mt-md-5 pt-md-5">
            <div class="col-md-11 col-12 col-lg-12">
                <div class="text-left">
                    <h5 class=" text-uppercase">Le corps Professoral de l'{{ $user_university->name_university}}</h5>
                </div>
            </div>
        </div>
        @foreach($data_teachers as $teacher)
        <div class="row">
            <div class="col-lg-3">
                @if($teacher->user->teacher !=null)
                <div class="card card-show-teacher">
                    <div class="card-header">
                        <div class="text-center">
                            <h4>{{$teacher->user->teacher->name_teacher}}</h4>
                        </div>
                        <div class="avatar-teacher">
                            <img src="/storage/uploads/avatars/{{$teacher->user->avatar}}" alt="img" class="img-cover">
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="text-center">
                            <span>{{$teacher->user->teacher->title->lampoon}}</span>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-center">
                        <a href="{{route('show_teacher',$teacher->user->teacher->id)}}" class="ouvrages text-center text-uppercase">
                            <!-- <span class="number">120</span>
                            <br> -->
                            <span>EN SAVOIR PLUS</span>
                        </a>
                        <!-- <div class="ouvrages text-center">
                            <span class="number">120</span>
                            <br>
                            <span>Articles</span>
                        </div>
                        <div class="ouvrages text-center">
                            <span class="number">120</span>
                            <br>
                            <span>Articles</span>
                        </div> -->
                    </div>
                </div>
                @else
                <div class="row  justify-content-center align-items-center  text-center">
                    <div class="col-md-12 mt-md-5 pt-md-5">
                        <div class="text-center">
                            <p class="text-center">Le professeur  n'existe pas !!! </p>
                        </div>
                    </div>
                </div>
                @endif
            </div>
        </div>
        @endforeach

        <div class="row justify-content-center">
            <div class="col-md-9 col-sm-6  p-5">
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>
            </div>
        </div>
    </div>


</div>

@endsection

@section('scriptis')
<script type="text/javascript" src="{{ asset('js/swiper.min.js') }}"></script>
<script>
    $(document).ready(function() {

        var swiper = new Swiper('.swiper-container', {
            effect: 'coverflow',
            grabCursor: true,
            centeredSlides: true,
            slidesPerView: 'auto',
            coverflowEffect: {
                rotate: 60,
                stretch: 0,
                depth: 400,
                modifier: 1,
                slideShadows: true,
            },
            pagination: {
                el: '.swiper-pagination',
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },

        });
    });
</script>
@endsection