routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $n_users = User::all();
    return view('welcome', compact('n_users'));
});

Route::get('/video', function () {
    return view('article.video');
});

// Route::get('welcome', 'HomeController@welcome')->name('welcome');

Route::get('mail', function () {
    Mail::send('message', array('name' => 'Arjun'), function ($messages) {
        $messages->to('webkoundo@gmail.com', 'Moses Bula')->subject('BookCase en oeuvre');
    });
});

//  Route auth avec verification de mail a utilisé en dev
// Auth::routes();

//  Route auth avec verification de mail a utilisé en prod
Auth::routes(['verify' => true]);

//  Route auth avec verification de mail a utilisé en prod
// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/choice', 'UserController@choice_compte')->name('choice');

//Après access choisir quel chemin prendre
Route::get('/path_user{user}', 'UserController@direction_user')->name('path_user');

// Pour le teacher
Route::resource('teacher', 'TeacherController');
Route::post('verif_teacher', 'TeacherController@verification')->name('verif_teacher');

Route::get('inquiry/{code}', 'TeacherController@inquiry')->name('inquiry');

Route::get('/teacher_create/{user}', 'TeacherController@student_create')->name('teacher');


// zone UNIVERSITY
Route::resource('university', 'UniversityController');
Route::resource('agreement', 'AgreementController');
Route::get('agreement_library', 'AgreementController@library')->name('agreement_library');

// library
Route::resource('library', 'LibraryController');

// End library

// Valider la demande de creation ave transmission de cote d'access
    
Route::get('validation/{code}', 'AgreementController@agreement')->name('validation');
Route::get('library_validate/{code}', 'AgreementController@validate_library')->name('library_validate');

// Route::post('v_agreement', 'AgreementController@validateagreement')->name('v_agreement');

// Route::get('dashboard', 'UniversityController@dashboard')->name('dashboard');

// Gestion d'artile d'une université (TFC,TFE, Memoire)
// Creation en function du dernier user inserer
Route::get('/student_create/{user}', 'StudentController@student_create')->name('student_create');
//REST student
Route::resource('student', 'StudentController');


Route::middleware('auth')->group(function(){
//  Route auth avec verification de mail a utilisé en dev
Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile')->name('profile');
Route::post('profile', 'UserController@update_profile')->name('profile');

// ZONE ETUDIANT

// connaitre la liste du corps professoral de l'university d'etude de l'etudiant
Route::get('univ_teacher', 'StudentController@univ_teacher')->name('univ_teacher');

// connaitre les details pertinents d'un corps professoral
Route::get('show_teacher/{id}', 'StudentController@show_teacher')->name('show_teacher');

// liste des news private
Route::get('private_news', 'StudentController@privatenews')->name('private_news');

// pour placer un article dans ses favoris
Route::get('articleFavoriteStoreToogle/{id}', 'ArticleController@article_favorite_store_toggle')->name('articleFavoriteStoreToogle');

//  End ZONE ETUDIANT

// news
Route::resource('news', 'NewsController');

Route::get('news_like/{id}', 'NewsController@like_to')->name('news_like');
Route::get('news_like_show/{id}', 'NewsController@like_to_show')->name('news_like_show');
Route::get('news_join_show/{id}', 'NewsController@join_to_show')->name('news_join_show');
Route::get('news_join/{id}', 'NewsController@join_to')->name('news_join');
Route::post('commentNews', 'NewsController@commetNews')->name('commentNews');

// Route::get('news_join/{id}','NewsController@join_to');

Route::resource('activation', 'ActivationController');
Route::get('activation_store/{id}', 'ActivationController@stor')->name('activation_store');
Route::get('act_destroy/{id}', 'ActivationController@act_destroy')->name('act_destroy');

//pedrien
Route::get('student_artcles', 'TeacherController@student_articles')->name('student_articles');

Route::get('dashboard', 'TeacherController@dashboard')->name('dashboard');

    // Zone article
    Route::resource('article', 'ArticleController');
    // delete article
    Route::get('article_delete/{id}', 'ArticleController@destroy')->name('article_delete');

    // Pour brouillon
    Route::get('draft', 'ArticleController@draft')->name('draft');

    // publication brouillon
    Route::post('draft_publish/{id}', 'ArticleController@draft_publish')->name('draft_publish');

    // Pour le welcome_article
    Route::post('article_home', 'ArticleController@article_welcome')->name('article_home');

    // Pour article : all, free et payant
    Route::get('article_show/{type}', 'ArticleController@article_show')->name('article_show');

  

    // Pour article :: all (par collections)
    Route::get('ArticleCollection', 'ArticleController@article_collections')->name('ArticleCollection'); //ici

    // Pour article : article_recent
    Route::get('article_recent', 'ArticleController@article_recent')->name('article_recent');

    // Pour article : article favorites
    Route::get('ArticleFavorites', 'ArticleController@article_favorites')->name('ArticleFavorites');

    // Pour article : download
    Route::get('download_file/{id}', 'ArticleController@download_file')->name('download_file');

    // Pour article payer
    Route::get('article_payer/{type}', 'ArticleController@paiement_recent')->name('Payment');

    // Article a payer
    Route::get('pay/{id}', 'ArticleController@payments')->name('pay');

    // Fin de zone ARTICLE

    // Library

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');
    // payer l'abonnement d'un bundle d'une library
    Route::post('pay_abonnement', 'LibraryController@pay_abonnement')->name('pay_abonnement');
    // pour student et autres utilisateurs en dehors de l'administration de la library
    Route::get('s_libraries/{datav?}', 'StudentController@s_libraries')->name('studentLibrary');

    // dashboard library
    Route::get('dashboardLibrary', 'LibraryController@dashboard')->name('dashboardLibrary');

    // End library


    // Teacher
    // get
    Route::get('TeacherRessource', 'UniversityController@teacher_ressource')->name('TeacherRessource');
    //enregistrer
    Route::post('teacherstore', 'UniversityController@teacherstore_reference')->name('teacherstore');
    // End Teacher


    // Dashbord de l'university
    Route::get('wall', 'UniversityController@dashboard')->name('wall');

    //get
    Route::get('ArticleRessource', 'UniversityController@article_ressource')->name('ArticleRessource');

    // Visualisation de toutes les univcersités par la communauté bookcase
    Route::get('universities', 'UniversityController@university_all')->name('universities');

    // Gestion student
    Route::get('StudentRessource', 'UniversityController@student_ressource')->name('StudentRessource');

    // get:  document
    Route::get('CollectionRessource','UniversityController@promotion_ressource')->name('CollectionRessource');

    // get:  department
    Route::get('DepartmentRessource','UniversityController@department_ressource')->name('DepartmentRessource');

    // get: faculty
    Route::get('FacultyRessource','UniversityController@faculty_ressource')->name('FacultyRessource');


    // Get: Facultés/Departements/Promotion d'une université
    Route::get('InstitutionRessource', 'UniversityController@instutition_ressource')->name('InstitutionRessource');

    // store Instutition : Faculté,Department et collection ou promotion
    Route::post('InstitutionStore','UniversityController@storeinstitution')->name('InstitutionStore');

    //Enregistrer une news
    // get
    Route::get('storeNews', 'UniversityController@storeNews')->name('storeNews');

    // enregistrer
    Route::post('newstore', 'UniversityController@store_news')->name('newstore');


    Route::resource('Cart', 'CartController');
    Route::get('add_panier/{id}', 'CartController@storeart')->name('add_panier');
    Route::get('CartEmpty', 'CartController@CartEmpty')->name('CartEmpty');
    Route::get('CartDestroy/{id}', 'CartController@destroy')->name('CartDestroy');
    Route::post('CartPay', 'CartController@CartPay')->name('CartPay');
    Route::post('PayConfirm', 'CartController@PayConfirm')->name('PayConfirm');
});

resources/views/univ/article_ressource.blade.php
@extends('layouts.student_layout')

@section('content_student')
<div class="container margin">
    <div class="row justify-content-center">
            <div class="col-md-11 col-11 col-lg-12">
                <div class="text-left">
                    <h1 class="title">Gestion d'article en ligne</h1>
                </div>
            </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-10" style="margin-top:-20px">
            <div class="card card_create_news">
                <img src="/storage/uploads/avatars/{{$university->logo_picture}}" alt="" class="avatar avatarforcard_create_new rounded-circle avatar_student_teach_univ">
                <div class="card-header" style="box-shadow:0px 1px 0px 0 rgba(0,0,0,.2)">
                   <div class="container">
                        <ul class="nav nav-tabs ml-auto" id="myTab" role="tablist" style="border-bottom:none!important;">
                            <li class="nav-item">
                                <a class="nav-link active nav_link" id="all-tab" data-toggle="tab" href="#all" role="tab" aria-controls="all" aria-selected="true"><i class="fa fa-users"></i>Articles publiés</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav_link" id="file-tab" data-toggle="tab" href="#file" role="tab" aria-controls="file" aria-selected="false"><i class="fa fa-file"></i>Créer Article</a>
                            </li>
                            
                        </ul>
                   </div>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="myTabContent">
                        <!-- All Articles -->
                        <div class="tab-pane fade show active" id="all" role="tabpanel" aria-labelledby="all-tab">
                            <div class="container">

                               <div class="card-body">
                                    <div class="text-center">
                                        <i class="fa fa-warning text-warning fa-2x"></i>
                                        <small>
                                            <p>
                                                All Articles
                                            </p>
                                        </small>
                                    </div>
                                </div>

                                <div class="text-center">
                                    <small class="load-text"></small>
                                    <span class="spinner-border-sm load" role="status" aria-hidden="true" ></span>
                                </div>
                                
                            </div>
                        </div>
                        <!-- Fin All Articles -->

                        <!-- Créer file -->
                        <!-- method="POST" action="{{route('article.store')}}"  -->
                        <div class="tab-pane fade" id="file" role="tabpanel" aria-labelledby="file-tab">
                            <div class="container pt-md-4">
                                <form method="POST" action="{{ route('article.store')}}" enctype="multipart/form-data" style="padding:20px 30px; position relative;">
                                    @csrf
                                    <div class="form-group row justify-content-center">
                                        <div class="col-md-6">
                                            <label for="title">Edition</label>
                                            <input type="number" name="edition" class="form-control">
                                            <input type="hidden" name="price" class="form-control" value="0">
                                            <input type="hidden" name="statut_id" id="statut_id" class="form-control" value="1">
                                            <input type="hidden" name="collect" id="collect" class="form-control" value="1">
                                        </div>
                                    </div>

                                    <div class="form-group row justify-content-center">
                                        <div class="col-md-6">
                                            <label for="title">Fichier / Fichiers</label>
                                            <div class="input-group mb-3">
                                                <!-- <div class="input-group-prepend">
                                                        <button class="btn btn-outline-secondary btn-sm" type="button" id="inputGroupFileAddon03">Télécharger</button>
                                                    </div> -->
                                                <div class="custom-file">
                                                    <input type="file" name="file_article[]" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03" accept=".pdf,.txt,.doc,.docx,.xml,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" multiple>
                                                    <label class="custom-file-label" for="inputGroupFile03">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group row justify-content-center">
                                        <div class="col-md-6">
                                            <label for="title">Catégorie</label>
                                            <!-- name=category_id[]   multiple si la selection passe a plusieurs-->
                                            <select class="form-control" id="category_id" name="category_id">
                                                @foreach($categories as $categor)
                                                <option value="{{$categor->id}}">{{$categor->category}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <br>
                                    </div>

                                    <div class="card-footer bg-white">
                                        <div class="container content-button pb-4 pt-4">
                                            <button type="submit" class="btn btn-primary btn-sm badge btn-save" style="background-color:#6f42c1 !important; border:none !important;"><i class="fa fa-plus"></i> Ajouter fichier(s)</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- Fin Créer file -->


                    </div>
                </div>                
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
</div>
@endsection

@section('scriptis')
<script>
    $(document).ready(function() {

        $('.custom-file-input').on('change', function(event) {
            var inputFile = event.currentTarget;
            $(inputFile).parent()
                .find('.custom-file-label')
                .html(inputFile.files[0].name);
                 });

        $('#title').change(function(){
            var title = $(this).val();
            $('#title_ap').text("Sujet : " + title.toString());
        });



        // Sa marche, reste la reinitialisation
        // var form_news_public  = document.getElementById('news_public');
        // var request_form = new XMLHttpRequest();

        // form_news_public.addEventListener('submit',function(e){
        //     e.preventDefault();
        //     var formdata  = new FormData(form_news_public);

        //     request_form.open('post',"{{route('newstore')}}");
        //     request_form.send(formdata);
        //     return false;
        // });
    });
</script>
@endsection

resources/views/univ/create.blade.php
@section('style')
<link href="{{ asset('css/_style.css') }}" rel="stylesheet">
@endsection

@extends('layouts.app',['title' => 'app'])

@section('content')
<div class="bg-choice">
    <div class="container">
        
        <div class="row justify-content-around">
            <div class="col-md-10 col-lg-5 bg-white">
                <ul id="progress">
                    <li>Account Setup</li>
                    <li class="active">Personal Details</li>

                </ul>

                <div class="card slideBox1" style="border-radius: 10px;padding:20px 30px;background:white;z-index: 1;">
                    <div class="text-left mb-4">

                        <h2 class="heading title-form page2" style="font-size: 28px;">University Account</h2>

                    </div>

                    <div class="card-body">
                        
                        <form method="POST" action="{{route('university.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row mb-4">
                                
                                <div class="col-md-12">
                                <label for="file_picture">Sigle</label>
                                <div class="input-group mb-3">
                                    <input type="text" name="sigle" class="form-control" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03">
                                </div>
                               
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                
                                <div class="col-md-6">
                                <label for="file_picture">Picture</label>
                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <input type="file" name="file_picture" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03" accept=".jpg,.jpeg,.png">
                                        <label class="custom-file-label" for="inputGroupFile03">Importer un fichier</label>
                                        <span class="btn-file"><i class="fa fa-image"></i></span>
                                    </div>
                                </div>
                                </div>
                                <div class="col-md-6">
                                   <label for="file_logo">logo</label>
                                   <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <input type="file" name="file_logo" class="custom-file-input" id="inputGroupFile03" aria-describedby="inputGroupFileAddon03" accept=".jpg,.jpeg,.png">
                                        <label class="custom-file-label" for="inputGroupFile03">Importer un fichier</label>
                                        <span class="btn-file"><i class="fa fa-image"></i></span>
                                    </div>
                                    </div>
                                </div> 
                            </div>
                            
                            <div class="form-group row  mb-4">
                                <div class="col-md-12">
                                    <label for="describe">Description</label>
                                    <textarea name="describe" id="describe" class="form-control" required></textarea>
                                </div>
                            </div>
                            <div class="form-group row  mb-4">
                                
                                <div class="col-md-12">
                                    <label for="adress">Adresse</label>
                                    <textarea name="adress" id="adress" class="form-control" required></textarea>
                                    <input type="hidden" name="user_id" id="user_id" value="{{$user->id}}">
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <div class="col-md-12">
                                    <label for="phone">Téléphone</label>
                                    <input id="phone" type="tel" class="form-control" name="phone"  required autocomplete="phone">
                                    
                                    <input type="hidden" id="agreem_id"  name="agreem_id" value="{{$agreement->id}}">
                                </div>
                            </div>
                            <div class="form-group row  mb-4">
                                
                                <div class="col-md-6">
                                    <label for="longitude">Longitude</label>
                                    <input id="longitude" type="number" class="form-control" name="longitude"  required autocomplete="phone">
                                </div>
                                <div class="col-md-6">
                                    <label for="latitude">Latitude</label>
                                    <input id="latitude" type="number" class="form-control" name="latitude"  required autocomplete="phone">
                                </div>

                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-block btn-auth btn-login btn-float">
                                <span class="spinner-border-sm rotate_spinner" role="status" aria-hidden="true" ></span>
                                <span class="spam">Sauvegarder les infos</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center mt-4">
            <small class="text-secondary">BookCase <?php echo strftime('%Y') ?> &copy;</small>

        </div>
    </div>
</div>
@endsection

@section('scriptis')
<script>
    $(document).ready(function() {
        $('.custom-file-input').on('change', function(event) {
            var inputFile = event.currentTarget;
            $(inputFile).parent()
                .find('.custom-file-label')
                .html(inputFile.files[0].name);
        });
    });

</script>
@endsection

resources/views/univ/department_ressource.blade.php
@extends('layouts.student_layout')

@section('content_student')
<div class="container margin">
    <div class="row justify-content-center">
            <div class="col-md-9 col-9 offset-md-3 col-lg-12">
                <div class="text-left">
                    <h1 class="title">Departments/Sections</h1>
                </div>
            </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-10" style="margin-top:-20px">
            <div class="card card_create_news">
                
                <div class="card-body mt-5">
                    <div class="tab-content" id="myTabContent">
                        
                        <!-- All Departments -->
                        <div class="tab-pane fade show active" id="teacher" role="tabpanel" aria-labelledby="teacher-tab">
                           
                            @if($departments->count()>0)
                            @foreach($departments as $department)
                            <div class="card-header bg-white card-header-avatar text-left" style="height: 100% !important;">
                                <div class="card-pseudo pseudo" style="font-weight:400;margin-left:30px!important">
                                    <i class="fa fa-bank fa-3x" style="color:#b1b1b1;">
                                    </i>
                                   <span class="pl-md-2" style="font-size:1.4em;">{{$department->title_department}}</span>
                                </div>

                                <div class="card-date function" style="margin-left:30px!important">
                                        <br>
                                        <span class="pl-5">* Faculté : {{$department->faculty->title}} </span>
                                </div>

                                <div class="card-date function pt-2" style="margin-left:30px!important">
                                        <strong class="pl-5">* Promotions </strong>
                                        <br>
                                        @foreach($collections as $document)
                                        @if($document->department_id == $department->id)
                                        <span class="pl-5 ml-2"> - {{$document->document_name}} </span>
                                        <br>
                                        @endif
                                        @endforeach
                                </div>

                                <div class="more">
                                    <span class="option"><i class="fa fa-ellipsis-h"></i></span>
                                    <div class="show-option">
                                        <i class="fa fa-comment-o"></i>
                                        <i class="fa fa-eye"></i>
                                        <!-- <i class="fa fa-trash text-danger" title="Supprimer" data-toggle="tooltip" data-placement="top"></i> -->
                                    </div>
                                </div>
                            </div>
                            @endforeach
                            @else
                            <div class="card-body">
                                <div class="text-center">
                                    <i class="fa fa-info text-info fa-5x pt-5 mt-md-5"></i>
                                    <small>
                                        <p>Vous ne disposez d'aucun département ou d'aucune section</p>
                                        <p>Veuillez en crée, a de fin d'utilisation</p>
                                    </small>
                                </div>
                            </div>
                            @endif
                        </div>
                        <!-- Close All Department -->

                    </div>
                </div>                
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
</div>
@endsection

resources/views/univ/notvalidate.blade.php
@extends('layouts.app',['title' => 'app'])

@section('content')
    <div class="container">
        <div class="row justify-content-center margin">
            <div class="col-md-6">
                <div class="card px-4 py-5 Up">
                    <div class="text-center" style="background: url('/storage/uploads/images/enfin plan2.jpg');">
                        <i class="fa fa-info" style="font-size:200px;"></i>
                        <p>
                            Votre droit de creation de compte n'est pas valide.<br>

                        @if(session()->has('notreference'))
                        <small>Veuillez consulter votre boite email, pour récuperer le droit d'accès. </small>
                        </p>
                        @else
                        <small>Veuillez consulter votre boite email, au cas ou vous aviez soumis une demande. </small>
                        </p>
                        <small> Pour soumettre une demande, veuillez suivre cliquez sur ce lien ci-dessous. </small>
                        <p>
                            <br>
                            <a href="{{ route('agreement.index')}}" class="px-4 py-2 btn-primary btn-sm">Soumettre une demande</a>
                        </p>
                        @endif
                    </div>

                    <!-- <h4>2. Validation d'admission</h4>
                    <p>Inserez le code de validité après récupération de celui-ci sur votre e-mail afin de créer votre compte Université/ Institut</p>
                    <button class="btn btn-primary btn-sm show-cardfordemande badge">cliquez içi</button> -->
                            <!-- <div class="container">
                                <form class="cardfordemande" method="POST" action="{{route('agreement.store')}}" enctype="multipart/form-data" style="">
                                    @csrf
                                    <div class="form-group row justify-content-center mb-4">
                                        <div class="col-md-12">
                                            

                                            @error('name_inst')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-primary btn-login btn-float hidden-card">
                                        Valider
                                    </button>
                                </form>
                            </div> -->
                </div> 
            </div>
                    

    </div>
@endsection