routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $n_users = User::all();
    return view('welcome', compact('n_users'));
});

Route::get('/video', function () {
    return view('article.video');
});

// Route::get('welcome', 'HomeController@welcome')->name('welcome');

Route::get('mail', function () {
    Mail::send('message', array('name' => 'Arjun'), function ($messages) {
        $messages->to('webkoundo@gmail.com', 'Moses Bula')->subject('BookCase en oeuvre');
    });
});

//  Route auth avec verification de mail a utilisé en dev
// Auth::routes();

//  Route auth avec verification de mail a utilisé en prod
Auth::routes(['verify' => true]);

//  Route auth avec verification de mail a utilisé en prod
// Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/choice', 'UserController@choice_compte')->name('choice');

//Après access choisir quel chemin prendre
Route::get('/path_user{user}', 'UserController@direction_user')->name('path_user');

// Pour le teacher
Route::resource('teacher', 'TeacherController');
Route::post('verif_teacher', 'TeacherController@verification')->name('verif_teacher');

Route::get('inquiry/{code}', 'TeacherController@inquiry')->name('inquiry');

Route::get('/teacher_create/{user}', 'TeacherController@student_create')->name('teacher');


// zone UNIVERSITY
Route::resource('university', 'UniversityController');
Route::resource('agreement', 'AgreementController');
Route::get('agreement_library', 'AgreementController@library')->name('agreement_library');

// library
Route::resource('library', 'LibraryController');

// End library

// Valider la demande de creation ave transmission de cote d'access
    
Route::get('validation/{code}', 'AgreementController@agreement')->name('validation');
Route::get('library_validate/{code}', 'AgreementController@validate_library')->name('library_validate');

// Route::post('v_agreement', 'AgreementController@validateagreement')->name('v_agreement');

// Route::get('dashboard', 'UniversityController@dashboard')->name('dashboard');

// Gestion d'artile d'une université (TFC,TFE, Memoire)
// Creation en function du dernier user inserer
Route::get('/student_create/{user}', 'StudentController@student_create')->name('student_create');
//REST student
Route::resource('student', 'StudentController');


Route::middleware('auth')->group(function(){
//  Route auth avec verification de mail a utilisé en dev
Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile')->name('profile');
Route::post('profile', 'UserController@update_profile')->name('profile');

// ZONE ETUDIANT

// connaitre la liste du corps professoral de l'university d'etude de l'etudiant
Route::get('univ_teacher', 'StudentController@univ_teacher')->name('univ_teacher');

// connaitre les details pertinents d'un corps professoral
Route::get('show_teacher/{id}', 'StudentController@show_teacher')->name('show_teacher');

// liste des news private
Route::get('private_news', 'StudentController@privatenews')->name('private_news');

// pour placer un article dans ses favoris
Route::get('articleFavoriteStoreToogle/{id}', 'ArticleController@article_favorite_store_toggle')->name('articleFavoriteStoreToogle');

//  End ZONE ETUDIANT

// news
Route::resource('news', 'NewsController');

Route::get('news_like/{id}', 'NewsController@like_to')->name('news_like');
Route::get('news_like_show/{id}', 'NewsController@like_to_show')->name('news_like_show');
Route::get('news_join_show/{id}', 'NewsController@join_to_show')->name('news_join_show');
Route::get('news_join/{id}', 'NewsController@join_to')->name('news_join');
Route::post('commentNews', 'NewsController@commetNews')->name('commentNews');

// Route::get('news_join/{id}','NewsController@join_to');

Route::resource('activation', 'ActivationController');
Route::get('activation_store/{id}', 'ActivationController@stor')->name('activation_store');
Route::get('act_destroy/{id}', 'ActivationController@act_destroy')->name('act_destroy');

//pedrien
Route::get('student_artcles', 'TeacherController@student_articles')->name('student_articles');

Route::get('dashboard', 'TeacherController@dashboard')->name('dashboard');

    // Zone article
    Route::resource('article', 'ArticleController');
    // delete article
    Route::get('article_delete/{id}', 'ArticleController@destroy')->name('article_delete');

    // Pour brouillon
    Route::get('draft', 'ArticleController@draft')->name('draft');

    // publication brouillon
    Route::post('draft_publish/{id}', 'ArticleController@draft_publish')->name('draft_publish');

    // Pour le welcome_article
    Route::post('article_home', 'ArticleController@article_welcome')->name('article_home');

    // Pour article : all, free et payant
    Route::get('article_show/{type}', 'ArticleController@article_show')->name('article_show');

  

    // Pour article :: all (par collections)
    Route::get('ArticleCollection', 'ArticleController@article_collections')->name('ArticleCollection'); //ici

    // Pour article : article_recent
    Route::get('article_recent', 'ArticleController@article_recent')->name('article_recent');

    // Pour article : article favorites
    Route::get('ArticleFavorites', 'ArticleController@article_favorites')->name('ArticleFavorites');

    // Pour article : download
    Route::get('download_file/{id}', 'ArticleController@download_file')->name('download_file');

    // Pour article payer
    Route::get('article_payer/{type}', 'ArticleController@paiement_recent')->name('Payment');

    // Article a payer
    Route::get('pay/{id}', 'ArticleController@payments')->name('pay');

    // Fin de zone ARTICLE

    // Library

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');

    Route::get('abonnements/{id}', 'LibraryController@abonnements')->name('abonnements');
    // payer l'abonnement d'un bundle d'une library
    Route::post('pay_abonnement', 'LibraryController@pay_abonnement')->name('pay_abonnement');
    // pour student et autres utilisateurs en dehors de l'administration de la library
    Route::get('s_libraries/{datav?}', 'StudentController@s_libraries')->name('studentLibrary');

    // dashboard library
    Route::get('dashboardLibrary', 'LibraryController@dashboard')->name('dashboardLibrary');

    // End library


    // Teacher
    // get
    Route::get('TeacherRessource', 'UniversityController@teacher_ressource')->name('TeacherRessource');
    //enregistrer
    Route::post('teacherstore', 'UniversityController@teacherstore_reference')->name('teacherstore');
    // End Teacher


    // Dashbord de l'university
    Route::get('wall', 'UniversityController@dashboard')->name('wall');

    //get
    Route::get('ArticleRessource', 'UniversityController@article_ressource')->name('ArticleRessource');

    // Visualisation de toutes les univcersités par la communauté bookcase
    Route::get('universities', 'UniversityController@university_all')->name('universities');

    // Gestion student
    Route::get('StudentRessource', 'UniversityController@student_ressource')->name('StudentRessource');

    // get:  document
    Route::get('CollectionRessource','UniversityController@promotion_ressource')->name('CollectionRessource');

    // get:  department
    Route::get('DepartmentRessource','UniversityController@department_ressource')->name('DepartmentRessource');

    // get: faculty
    Route::get('FacultyRessource','UniversityController@faculty_ressource')->name('FacultyRessource');


    // Get: Facultés/Departements/Promotion d'une université
    Route::get('InstitutionRessource', 'UniversityController@instutition_ressource')->name('InstitutionRessource');

    // store Instutition : Faculté,Department et collection ou promotion
    Route::post('InstitutionStore','UniversityController@storeinstitution')->name('InstitutionStore');

    //Enregistrer une news
    // get
    Route::get('storeNews', 'UniversityController@storeNews')->name('storeNews');

    // enregistrer
    Route::post('newstore', 'UniversityController@store_news')->name('newstore');


    Route::resource('Cart', 'CartController');
    Route::get('add_panier/{id}', 'CartController@storeart')->name('add_panier');
    Route::get('CartEmpty', 'CartController@CartEmpty')->name('CartEmpty');
    Route::get('CartDestroy/{id}', 'CartController@destroy')->name('CartDestroy');
    Route::post('CartPay', 'CartController@CartPay')->name('CartPay');
    Route::post('PayConfirm', 'CartController@PayConfirm')->name('PayConfirm');
});

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $fillable = ['name_teacher', 'sex', 'phone', 'domain_exploitation', 'visibilities', 'title_id', 'user_id'];


    /* Relations */
    public function articles()
    {
        return  $this->hasMany('App\Article');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function title()
    {
        return $this->belongsTo('App\Title');
    }

    //Attributes
    public function setNameTeacherAttribute($value)
    {
        $this->attributes['name_teacher'] = ucfirst($value);
    }

    public function getNameTeacherAttribute($value)
    {
        return ucfirst($value);
    }

    public function setDomainExploitationAttribute($value)
    {
        $this->attributes['domain_exploitation'] = str_replace(",", "-",  strtoupper($value) . ',' . strtolower($value) . ',' . ucfirst($value));
    }

    // Fin Attributes


    /* Scopes */
    public function scopeSearchByTeacher($query, $q)
    {
        return $query->where('name_teacher', 'LIKE', '%' . $q . '%')
            ->orwhere('domain_exploitation', 'LIKE', '%' . $q . '%')
            ->orderBy('name_teacher');
    }
}

resources/views/teacher/create.blade.php
@section('style')
<link href="{{ asset('css/_style.css') }}" rel="stylesheet">
@endsection

@extends('layouts.app',['title' => 'Teacher'])

@section('content')
<div style="background:url('/storage/uploads/images/bgdiv.jpg');
    background-size: content;" id="div_general">

    <div class="container" style="margin-top:100px;" id="container-max">
        <div class="row justify-content-center">
            <div class="col-md-4  text-center">

                <div class="alert alert-info alert-dismissible alert-show fade-right">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div class="text-center">
                        <p class="h5  lead"> Bonjour <strong class="text_user_name">{{ $user->name }}</strong>, et bienvenue au <strong class="text-acceuil">BookCase !</strong></p>
                        <p class="h6">Aider nous à faire une plus ample connaissance de vous,
                            <br>
                            <span class="h6"> afin d'ameliorer la <span style="color:#3f4161">qualité</span> de <span style="color:#3f4161">nos services</span> et satisfaire au mieux à <span style="color:#3f4161">vos attentes</span>.</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row justify-content-around">
            <div class="col-md-10 col-lg-6">

                <div class="card" style="border-radius: 10px;padding:20px 30px;margin-top:20px">

                    <!-- {{ __('Register') }} -->
                    <div class="card-body">

                        <form method="POST" action="{{ route('teacher.store')}}">
                            @csrf
                            <div class="form-group row justify-content-center mb-4">

                                <div class="col-md-12">
                                    <input id="name_teacher" type="text" class="form-control" name="name_teacher" required placeholder="Nom Complet" value="{{ old('name_teacher')}}">
                                    <input id="reference" type="hidden" class="form-control" name="reference" required value="{{ $reference->id}}">
                                    {!! $errors->first('name_teacher','<p class="error-msg">:message</p>') !!}
                                    <!-- @error('student_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror -->
                                </div>
                            </div>

                            <div class="form-group  row justify-content-center mb-2">

                                <label for="sex" class="col-md-4 text-left col-6 col-lg-5">
                                    <input type="radio" name="sex" id="sex" class="form-check-input " value="M">Homme <i class="fa fa-male"></i>
                                </label>

                                <label for="sex" class="col-md-4  form-check-label text-left col-6 col-lg-5">
                                    <input type="radio" name="sex" id="sex" class="form-check-input" value="F">Femme <i class="fa fa-female"></i>
                                </label>

                                @error('sex')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>

                            <div class="form-group row justify-content-center mb-4">

                                <div class="col-md-12">
                                    <input id="phone" type="tel" class="form-control" name="phone" placeholder="Phone" required autocomplete="phone">
                                </div>

                            </div>

                            <div class="form-group row justify-content-center mb-4">

                                <div class="col-md-12">
                                    <textarea name="domain_exploitation" id="domain_exploitation" class=" @error('domain_exploitation') is-invalid @enderror form-control" required placeholder="Domaine d'exploitation, Ex: art - informatique - science - batiment - sculpture - musique"></textarea>
                                    <input type="hidden" name="user_id" id="user_id" value="{{$user->id}}">
                                    @error('domain_exploitation')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row justify-content-center">
                                <div class="col-md-12 mb-2">
                                    <select class="form-control" id="title_id" name="title_id">
                                        <!-- <option value="Titre">Titre</option> -->
                                        @foreach($titles as $title)
                                        <option value="{{$title->id }}">{{$title->lampoon }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <br>
                            </div>

                            <div class="form-group row justify-content-center">

                                <label for="mail_visibility" class="col-md-4 text-left col-6 col-lg-5" style="font-size:12px;">
                                    <input type="checkbox" name="mail_visibility" id="mail_visibility" class="form-check-input" value="true">Rendre visible votre Email
                                </label>

                                <label for="phone_visibility" class="col-md-4  form-check-label text-left col-6 col-lg-5" style="font-size:12px;">
                                    <input type="checkbox" name="phone_visibility" id="phone_visibility" class="form-check-input" value="true">Rendre visible votre numéro de téléphone
                                </label>
                            </div>
                            <div class="from-group row justify-content-center">
                                <div class="col-md-7">
                                    <button type="submit" class="btn btn-primary btn-block btn-auth btn-login">
                                        Sauvegarder vos infos
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>

</div>

@endsection

resources/views/teacher/student_articles.blade.php
styddidiid